version: 10.0.{build}
image: Visual Studio 2017
configuration: Release
install:
- ps: >-
    cd src
    
    nuget restore Humidifier.sln
    
    $env:HUMIDIFIER_BUILD_NUMBER = ([int]$env:APPVEYOR_BUILD_NUMBER).ToString("000")
    
    $env:HUMIDIFIER_VERSION_SUFFIX = "pre$env:HUMIDIFIER_BUILD_NUMBER"
    
    $env:appveyor_nuget_push = 'false'
    
    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      if($env:appveyor_repo_tag -eq 'True') {
        if($env:appveyor_repo_tag_name -match '^v[0-9]') {
           $env:appveyor_nuget_push = 'true'
           $env:HUMIDIFIER_VERSION_SUFFIX = ""
        }
        if($env:appveyor_repo_tag_name -eq 'latest') {
           $env:appveyor_nuget_push = 'true'
        }
      }
    }
build:
  project: src/Humidifier.sln
  verbosity: minimal
before_package:
- cmd: >-
    msbuild /t:pack /p:IncludeSymbols=true /p:VersionSuffix="%HUMIDIFIER_VERSION_SUFFIX%" /p:Configuration=Release Humidifier/Humidifier.csproj
    
    msbuild /t:pack /p:IncludeSymbols=true /p:VersionSuffix="%HUMIDIFIER_VERSION_SUFFIX%" /p:Configuration=Release Humidifier.Json/Humidifier.Json.csproj
artifacts:
- path: src\Humidifier\Bin\Release\*.nupkg
- path: src\Humidifier.Json\Bin\Release\*.nupkg
  
deploy:
- provider: NuGet
  api_key:
    secure: 4Lqb8mykTgZNLC3NX5EZlLnEYKGw5xnnDbM5ZaXEdQCUfU23MvK6aOI8b0z5Dx1V
  on:
    appveyor_nuget_push: true